# $OpenBSD:

COMMENT =	Wrap OP check callbacks

MODULES =	cpan
DISTNAME = B-Hooks-OP-Check-0.18
CATEGORIES =	devel

MAINTAINER = Erik Johansen <lemnayde@mnology.com>

# Perl
PERMIT_PACKAGE_CDROM =		Yes
PERMIT_PACKAGE_FTP =		Yes
PERMIT_DISTFILES_CDROM =	Yes
PERMIT_DISTFILES_FTP =		Yes

.include <bsd.port.mk>
