# $OpenBSD:

COMMENT = Getopt::Long with usage text

MODULES =	cpan
DISTNAME = Getopt-Long-Descriptive-0.082
CATEGORIES =	devel

MAINTAINER = Erik Johansen <lemnayde@mnology.com>

# Perl
PERMIT_PACKAGE_CDROM =		Yes
PERMIT_PACKAGE_FTP =		Yes
PERMIT_DISTFILES_CDROM =	Yes
PERMIT_DISTFILES_FTP =		Yes

RUN_DEPENDS = ${BUILD_DEPENDS}
BUILD_DEPENDS = ::devel/p5-Params-Validate \
	::devel/p5-Sub-Exporter

.include <bsd.port.mk>
