# $OpenBSD:

COMMENT =	Easily build XS extensions that depend on XS extensions

MODULES =	cpan
DISTNAME = ExtUtils-Depends-0.302
CATEGORIES =	devel

MAINTAINER = Erik Johansen <lemnayde@mnology.com>

# Perl
PERMIT_PACKAGE_CDROM =		Yes
PERMIT_PACKAGE_FTP =		Yes
PERMIT_DISTFILES_CDROM =	Yes
PERMIT_DISTFILES_FTP =		Yes

.include <bsd.port.mk>
