# $OpenBSD:

COMMENT =  Force coercion when validating type constraints

MODULES =	cpan
DISTNAME =  MooseX-Meta-TypeConstraint-ForceCoercion-0.01
CATEGORIES =	devel

MAINTAINER = Erik Johansen <lemnayde@mnology.com>

# Perl
PERMIT_PACKAGE_CDROM =		Yes
PERMIT_PACKAGE_FTP =		Yes
PERMIT_DISTFILES_CDROM =	Yes
PERMIT_DISTFILES_FTP =		Yes

RUN_DEPENDS = ${BUILD_DEPENDS}
BUILD_DEPENDS = ::devel/p5-namespace-autoclean \
	::devel/p5-Moose

.include <bsd.port.mk>
