# $OpenBSD:

COMMENT = Accurately serialize a data structure as Perl code.

MODULES =	cpan
DISTNAME = Data-Dump-Streamer-2.09
CATEGORIES =	devel

MAINTAINER = Erik Johansen <lemnayde@mnology.com>

# Perl
PERMIT_PACKAGE_CDROM =		Yes
PERMIT_PACKAGE_FTP =		Yes
PERMIT_DISTFILES_CDROM =	Yes
PERMIT_DISTFILES_FTP =		Yes

RUN_DEPENDS = ${BUILD_DEPENDS}
BUILD_DEPENDS = ::devel/p5-B-Utils

.include <bsd.port.mk>
