# $OpenBSD:

COMMENT=	roles with composition parameters

MODULES=	cpan
DISTNAME=	MooseX-Role-Parameterized-0.13
CATEGORIES=	devel

# perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

CPAN_AUTHOR= SARTAK

RUN_DEPENDS= ::devel/p5-Moose
REGRESS_DEPENDS= ::devel/p5-Test-Exception
		
.include <bsd.port.mk>
