# $OpenBSD:

COMMENT = automatically give your module the ability to have plugins

MODULES =	cpan
DISTNAME = Module-Pluggable-3.9
CATEGORIES =	devel

MAINTAINER = Erik Johansen <lemnayde@mnology.com>

# Perl
PERMIT_PACKAGE_CDROM =		Yes
PERMIT_PACKAGE_FTP =		Yes
PERMIT_DISTFILES_CDROM =	Yes
PERMIT_DISTFILES_FTP =		Yes

.include <bsd.port.mk>
