# $OpenBSD:

COMMENT =	Basic utilities for writing tests.

MODULES =	cpan
DISTNAME = Test-Simple-0.88
CATEGORIES =	devel

MAINTAINER = Erik Johansen <lemnayde@mnology.com>

# Perl
PERMIT_PACKAGE_CDROM =		Yes
PERMIT_PACKAGE_FTP =		Yes
PERMIT_DISTFILES_CDROM =	Yes
PERMIT_DISTFILES_FTP =		Yes

CONFIGURE_ARGS += INSTALLPRIVLIB=/usr/local/./libdata/perl5

.include <bsd.port.mk>
